# Generated by Django 5.2 on 2025-04-05 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('passw', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='signup_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='login',
        ),
        migrations.AddField(
            model_name='login_details',
            name='signUp_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Login.signup_details'),
        ),
    ]
