# Generated by Django 5.2 on 2025-04-05 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='signUp_details',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Login.signup_details'),
            preserve_default=False,
        ),
    ]
